# pipeline/roles.py

_RAW_ROLES = [
    "Accountant - Management - Accountancy - Business, Management, Admin and Support",
    "Accountant - Private Practice - Accountancy",
    "Accountant - Public Sector - Accountancy",
    "Accounting Technician - Accountancy",
    "Accounts Assistant - Financial Services",
    "Actor - Drama and Theatre Technology",
    "Actuary - Financial Services",
    "Acupuncturist - Alternative Medicine",
    "Administrative Assistant or Officer - Courts - Legal Support Services",
    "Advertising Account Executive - Advertising, Marketing and PR",
    "Advertising Account Planner - Advertising, Marketing and PR",
    "Advertising Copywriter - Advertising, Marketing and PR",
    "Advice Worker - Advisory Services",
    "Advocate - Law (Professional)",
    "Advocates' Clerk - Legal Support Services",
    "Aerospace Engineer - Aeronautical Engineering",
    "Agricultural Consultant - Agriculture",
    "Agricultural Scientist - Agriculture",
    "Air Cabin Crew - Air Transport",
    "Air Conditioning Engineer - Engineering General",
    "Air Quality Consultant - Environmental Services",
    "Air Traffic Controller - Air Transport",
    "Aircraft Maintenance Technician - Aeronautical Engineering",
    "Airline or Airport Passenger Service Assistant - Air Transport",
    "Airline Pilot - Air Transport",
    "Ambulance Care Assistant - Ambulance Services",
    "Ambulance Technician - Ambulance Services",
    "Anatomical Pathology Technologist - Medical Technology",
    "Animal Care Assistant - Work with Animals",
    "Animal Technician - Work with Animals - Science General",
    "Animator - Fine Art or Graphic Design",
    "Applications Developer - Programming and Development",
    "Arborist - Horticulture and Landscaping",
    "Archaeologist - Culture and Heritage",
    "Architect - Architecture",
    "Architectural Technologist - Architecture",
    "Archivist - Libraries and Information Science - Media and Broadcasting",
    "Army – Officer - Armed Services",
    "Army – Soldier - Armed Services",
    "Aromatherapist - Wellbeing",
    "Art Therapist - Therapists",
    "Artificial Intelligence Specialist/Engineer - Programming and Development",
    "Arts Administrator - Arts Administration",
    "Assembler - Electronics - Electrical and Electronic Engineering",
    "Assistance Dog Trainer - Work with Animals",
    "Astronomer or Astrophysicist - Physics",
    "Auctioneer - Retail and Sales",
    "Audiologist - Medical Technology",
    "Automotive Engineer - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Bank or Building Society Customer Adviser - Financial Services",
    "Bank or Building Society Manager - Financial Services",
    "Bar Worker - Hospitality",
    "Barber - Hairdressing",
    "Beauty Therapist - Beauty",
    "BIM Technician - Building Technology and Management",
    "Biochemist - Biology",
    "Biologist - Biology",
    "Biomedical Scientist - Medical Technology",
    "Biomedical Support Worker - Medical Technology",
    "Biotechnologist - Biology",
    "Blacksmith - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Blockchain Developer - Programming and Development",
    "Boat or Ship Builder - Naval Architecture and Marine Engineering",
    "Body Piercer - Beauty",
    "Border Force Officer - Police and Security Work",
    "Botanist - Biology - Horticulture and Landscaping",
    "Brewery Worker - Food and Drink Manufacturing",
    "Bricklayer - Construction Crafts",
    "British Sign Language Interpreter - Languages",
    "Broadcast Assistant - Media and Broadcasting",
    "Broadcast Engineer - Electrical and Electronic Engineering - Media and Broadcasting",
    "Broadcast Journalist - Journalism - Media and Broadcasting",
    "Builders' Merchant - Retail and Sales",
    "Building Services Engineer - Building Technology and Management",
    "Building Standards Surveyor - Surveying",
    "Building Technician - Building Technology and Management",
    "Bus or Coach Driver - Road Transport",
    "Business Adviser - Business, Management, Admin and Support",
    "Butcher - Retail and Sales - Food and Drink Manufacturing",
    "Cabinet Maker - Furniture",
    "CAD Technician - Engineering General",
    "Call Centre Agent - Call Centres",
    "Camera Operator - Media and Broadcasting",
    "Car Valet - Vehicle Related Services",
    "Cardiac Physiologist - Medical Technology",
    "Care Assistant or Support Worker - Social Work or Social Care",
    "Care Home Manager - Social Work or Social Care",
    "Careers Adviser - Advisory Services",
    "Cartographer - Surveying",
    "Casino Dealer - Leisure",
    "Catering Manager - Hospitality",
    "CCTV Operator - Police and Security Work",
    "Ceiling Fixer - Construction Crafts",
    "Cemetery Worker - General Services",
    "Ceramic Designer - 3 Dimensional Design",
    "Character Artist - Fine Art or Graphic Design - Web and Multimedia",
    "Charity Fundraiser - Advertising, Marketing and PR",
    "Chef or Cook - Hospitality",
    "Chemical Engineer - Chemical and Materials Engineering",
    "Chemical Engineering Technician - Chemical and Materials Engineering",
    "Chemical Plant Process Operative - Chemical and Materials Engineering",
    "Chemist - Chemistry and Materials Science",
    "Childminder - Childcare and Education",
    "Children’s Holiday Representative - Travel and Tourism - Childcare and Education",
    "Chiropractor - Alternative Medicine",
    "Choreographer - Dance",
    "Cinema or Theatre Assistant - Leisure",
    "Cinema or Theatre Manager - Leisure",
    "Civil Engineer - Civil and Structural Engineering",
    "Civil Engineering Technician - Civil and Structural Engineering",
    "Civil Service Administrative Assistant and Officer - Public Services Administration",
    "Civil Service Administrator - Fast Stream - Public Services Administration",
    "Classroom Assistant - Primary or Early Years - Education Support",
    "Cleaner - Property Services",
    "Clerical or Administrative Assistant - Administration and Management General",
    "Clerk of Court - Legal Support Services",
    "Clerk of Works - Building Technology and Management",
    "Clinical and Biomedical Engineer - Medical Technology",
    "Clinical Perfusionist - Medical Technology",
    "Clinical Photographer - Photography",
    "Clinical Technologist (Clinical Engineering) - Medical Technology",
    "Cloud Engineer - Programming and Development - Systems and Networks - Web and Multimedia",
    "CNC Machinist - Mechanical and Manufacturing Engineering (including Fabrication and Welding) - Engineers and Engineering Operatives or Technicians",
    "Coastguard - Emergency Services",
    "Commissioning Editor - Publishing and Writing",
    "Community Arts Worker - Community Arts",
    "Community Learning and Development Officer - Community Work",
    "Community Warden - Police and Security Work",
    "Community Waste Officer - Environmental Services",
    "Company Secretary - Administration and Management General",
    "Composer or Songwriter - Music",
    "Conference Producer - Advertising, Marketing and PR",
    "Construction Manager or Site Manager - Building Technology and Management",
    "Construction Plant Mechanic - Engineering General",
    "Control and Instrumentation Engineer - Electrical and Electronic Engineering",
    "Copy Editor - Publishing and Writing",
    "Costume Designer - Fashion or Textile Design - Drama and Theatre Technology",
    "Counsellor - Psychology and Counselling",
    "Countryside Ranger or Warden - Environmental and Rural Resource Management",
    "Craft Designer - 3 Dimensional Design",
    "Credit Manager - Financial Services",
    "Crematorium Technician - Personal Services",
    "Crime Scene Examiner - Police and Security Work",
    "Customer Service Administrator - Administration and Management General",
    "Cyber Security Analyst - IT Security - Digital and Technology",
    "Cycle Mechanic - Vehicle Maintenance and Repair",
    "Data Analyst - Computing General - Mathematics and Statistics - Digital and Technology",
    "Data Protection Officer - IT Security",
    "Data Scientist - Mathematics and Statistics - Computing General - Digital and Technology",
    "Database Administrator - Programming and Development",
    "Decontamination Technician - Medical Technology",
    "Delivery Driver - Distribution",
    "Demolition Operative - Construction Crafts",
    "Dental Hygienist or Therapist - Dentistry",
    "Dental Nurse - Dentistry",
    "Dental Technician - Dentistry",
    "Dentist - Dentistry",
    "Derrickhand - Offshore and Energy - Offshore Based",
    "Design Engineer - Engineering General",
    "Dietetic Support Worker - Dietetics",
    "Dietitian - Dietetics",
    "Digital Content Editor - Publishing and Writing",
    "Digital Marketer - Advertising, Marketing and PR",
    "Diplomatic Service Operational Officer - Public Services Administration",
    "Disc Jockey – DJ - Music Technology - Media and Broadcasting",
    "Dispensing Optician - Ophthalmics and Orthoptics",
    "Distillery Worker - Food and Drink Manufacturing",
    "Diver - Offshore and Energy - Sport and Fitness - Offshore Based",
    "Dryliner - Construction Crafts",
    "Dynamic Positioning Operator - Sea Transport",
    "Early Years Practitioner - Childcare and Education",
    "Economic Development Officer - Public Services Administration",
    "Economist - Economics",
    "Electrical Engineer - Electrical and Electronic Engineering",
    "Electrical or Electronic Engineering Technician - Electrical and Electronic Engineering",
    "Electrical Project Engineer - Engineers and Engineering Operatives or Technicians",
    "Electrician - Electrical and Electronic Engineering",
    "Electricity Distribution Worker - Electrical and Electronic Engineering",
    "Electronics Engineer - Electrical and Electronic Engineering",
    "Embalmer - Science General",
    "Emergency Call Handler - Ambulance Services",
    "Engineering Operative - Mechanical and Manufacturing Engineering (including Fabrication and Welding) - Manufacturing General",
    "Environment and Compliance Adviser - Environment, Health and Safety",
    "Environmental Consultant - Environmental Services",
    "Environmental Health Officer - Environmental Services",
    "Environmental Manager - Environmental and Rural Resource Management",
    "Environmental Specialist Decommissioning - Environment, Health and Safety",
    "Ergonomist - Engineering General - 3 Dimensional Design",
    "ESG (Environmental, Social and Governance) Analyst - Environment, Health and Safety",
    "Estate Agent - Property Services",
    "Estate or Land Manager - Agriculture",
    "Estimator - Building Technology and Management - Business, Management, Admin and Support",
    "Events Manager - Advertising, Marketing and PR - Arts Administration",
    "Exhibition Designer - Interior Design or Display",
    "Export Sales Manager - Retail and Sales",
    "Fabric Cutter - Clothing and Textiles",
    "Fabricator or Plater - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Facilities Manager - Facilities Management",
    "Farm Manager - Agriculture",
    "Farm Worker or Stockperson - Agriculture",
    "Farrier - Work with Animals",
    "Fashion Designer - Fashion or Textile Design",
    "Fashion Model - Advertising, Marketing and PR",
    "Field Engineer - Engineers and Engineering Operatives or Technicians",
    "Field Service Technician - Mechanical and Manufacturing Engineering (including Fabrication and Welding) - Electrical and Electronic Engineering",
    "Field Team Manager - Engineers and Engineering Operatives or Technicians",
    "Film or Video Editor - Media and Broadcasting",
    "Financial Adviser - Financial Services",
    "Fine Artist - Fine Art or Graphic Design",
    "Firefighter - Emergency Services",
    "Fish Farm Manager - Aquaculture and Fishing",
    "Fish Farm Worker - Aquaculture and Fishing",
    "Fishing Vessel Worker - Aquaculture and Fishing",
    "Fitness Instructor - Sport and Fitness",
    "Flight Dispatcher - Air Transport",
    "Floor Layer or Carpet Fitter - Construction Crafts",
    "Floor Manager – Television - Media and Broadcasting",
    "Florist - Retail and Sales",
    "Food Scientist or Technologist - Food Science and Technology - Food and Drink Manufacturing",
    "Forensic Computer Analyst - IT Security",
    "Forensic Scientist - Chemistry and Materials Science - Biology",
    "Forest or Wildlife Manager - Arboriculture and Forestry",
    "Forest or Wildlife Ranger - Arboriculture and Forestry",
    "Forest Worker - Arboriculture and Forestry",
    "Forklift Truck Operator - Distribution",
    "Formworker - Construction Crafts",
    "Freight Forwarder - Distribution",
    "Front End Developer - Web and Multimedia",
    "Fundraising Manager - Advertising, Marketing and PR - Business, Management, Admin and Support",
    "Funeral Director - Personal Services",
    "Furniture Designer - 3 Dimensional Design",
    "Gamer",
    "Gamekeeper - Environmental and Rural Resource Management",
    "Games Designer - Web and Multimedia",
    "Games Programmer - Web and Multimedia",
    "Games Tester - Web and Multimedia",
    "Garden Centre Worker - Retail and Sales",
    "Gardener - Horticulture and Landscaping",
    "Garment or Textile Technologist - Clothing and Textiles",
    "Gas Heating Engineer - Offshore and Energy",
    "Gas Service Engineer - Offshore and Energy",
    "General Construction Operative - Construction Crafts",
    "Geneticist - Biology",
    "Geologist - Earth Studies - Subsurface Scientists",
    "Geophysicist - Physics - Subsurface Scientists",
    "Geoscientist - Subsurface Scientists - Earth Studies",
    "Glass Designer or Maker - 3 Dimensional Design",
    "Glazier - Construction Crafts",
    "Glazing Technician - Vehicle Maintenance and Repair",
    "Goft Trainer",
    "Goft Professional",
    "Goft Teacher",
    "Goft Analyst",
    "Goft Coach",
    "Goft Instructor",
    "Goft Manager",
    "Goft Player",
    "Goft Referee",
    "Goft Scout",
    "Goft Writer",
    "Goft Agent",
    "Government Intelligence Officer or Analyst - Police and Security Work",
    "Graphic Designer - Fine Art or Graphic Design",
    "Groundsperson - Horticulture and Landscaping",
    "Gym Instructor - Sport and Fitness",
    "Hair Stylist - Hairdressing",
    "Health and Safety Inspector - Environmental Services",
    "Health and Safety Officer - Environmental Services",
    "Health Improvement Officer - Nursing and Auxiliary Work",
    "Health Records Staff - Public Services Administration",
    "Health Service Manager - Public Services Administration",
    "Health Visitor or Public Health Nurse - Nursing and Auxiliary Work",
    "Heating and Ventilation Engineer - Engineering General",
    "Helicopter Pilot - Air Transport - Transport and Logistics",
    "Herbalist - Alternative Medicine",
    "Holiday Centre Worker - Travel and Tourism",
    "Home Media Engineer - Electrical and Electronic Engineering",
    "Homeopath - Alternative Medicine",
    "Horticultural Scientist - Horticulture and Landscaping - Arboriculture and Forestry",
    "Hospital Porter - Nursing and Auxiliary Work",
    "Hotel General Manager - Hospitality",
    "Hotel Porter - Hospitality",
    "Hotel Receptionist - Hospitality",
    "Housekeeping Manager - Hospitality",
    "Housing Officer - Social Work or Social Care",
    "Human Resources Officer or Manager - Human Resource Management - Business, Management, Admin and Support",
    "Hydraulic Technician - Engineers and Engineering Operatives or Technicians",
    "Hydrogen Project Development Officer - Business, Management, Admin and Support",
    "Hypnotherapist - Alternative Medicine",
    "Illustrator - Fine Art or Graphic Design",
    "Immigration Enforcement Officer - Police and Security Work",
    "Insurance Account Manager - Financial Services",
    "Insurance Broker - Financial Services",
    "Insurance Claims Handler - Financial Services",
    "Insurance Loss Adjuster - Financial Services",
    "Insurance Risk Surveyor - Financial Services",
    "Insurance Underwriter - Financial Services",
    "Integrity Engineer - Engineers and Engineering Operatives or Technicians - Offshore and Energy",
    "Interior Designer - Interior Design or Display",
    "Interpreter - Languages",
    "Investment Analyst - Financial Services",
    "Investment Banker - Financial Services",
    "Investment Operations Administrator - Financial Services",
    "IT Helpdesk Analyst - IT Support",
    "IT Support Engineer - IT Support",
    "Jeweller - Retail - Retail and Sales",
    "Jewellery Designer - 3 Dimensional Design",
    "Joiner or Carpenter - Construction Crafts",
    "Journalist or Reporter - Journalism",
    "Judge or Sheriff - Law (Professional)",
    "Kitchen Assistant - Hospitality",
    "Laboratory Technician - Science General",
    "Landbased Service Engineer - Engineering General",
    "Landscape Architect - Landscape Architecture",
    "Landscaper - Horticulture and Landscaping",
    "Learning Support Assistant - Education Support",
    "Lecturer - Further Education - College or University Lecturing",
    "Lecturer - Higher Education - College or University Lecturing",
    "Legal Secretary - Administration and Management General",
    "Librarian or Information Professional - Libraries and Information Science",
    "Library or Information Assistant - Libraries and Information Science",
    "Lifeguard or Pool Attendant - Sport and Fitness",
    "Lighting Technician - Media and Broadcasting - Drama and Theatre Technology",
    "Lightning Protection Engineer - Electrical and Electronic Engineering",
    "Literary Agent - Publishing and Writing",
    "Local Government Administrative Assistant or Officer - Public Services Administration",
    "Local Government Officer - Public Services Administration",
    "Locksmith - Property Services",
    "Loft and Cavity Insulation Technician - Construction Crafts",
    "Logistics Manager - Distribution - Transport and Logistics",
    "Lorry or LGV Driver - Distribution",
    "Machine Printer - Printing",
    "Make-up Artist - Beauty",
    "Management Consultant - Administration and Management General",
    "Manufacturing Systems Engineer - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Marine Biologist - Biology",
    "Marine Engineer - Naval Architecture and Marine Engineering",
    "Market Research Executive - Advertising, Marketing and PR",
    "Market Research Interviewer - Advertising, Marketing and PR",
    "Marketing Manager - Advertising, Marketing and PR",
    "Mastic Asphalter - Construction Crafts",
    "Materials Scientist or Engineer - Chemistry and Materials Engineering",
    "Maternity Support Worker - Nursing and Auxiliary Work",
    "Mathematician - Mathematics and Statistics",
    "Meat Process Worker - Food and Drink Manufacturing",
    "Mechanical Engineer - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Mechanical Engineering Technician - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Medical Pathologist - Medicine and Surgery",
    "Medical Physicist - Medical Technology",
    "Medical Representative - Retail and Sales - Medical Technology",
    "Medical Secretary - Administration and Management General",
    "Member of Parliament - Politics",
    "Merchant Navy Deck Officer - Sea Transport",
    "Merchant Navy Engineering Officer - Sea Transport",
    "Merchant Navy Rating - Sea Transport",
    "Meteorologist - Earth Studies",
    "Meter Reader - Property Services",
    "Microbiologist - Biology",
    "Midwife - Nursing and Auxiliary Work",
    "Model Maker - 3 Dimensional Design",
    "Motor Vehicle Technician - Vehicle Maintenance and Repair",
    "Motorcycle Instructor - Road Transport",
    "Motorcycle Technician - Vehicle Maintenance and Repair",
    "Mudlogger - Offshore and Energy - Offshore Based",
    "Museum Assistant or Visitor Assistant - Culture and Heritage",
    "Museum Conservation Officer - Culture and Heritage",
    "Museum or Art Gallery Curator - Culture and Heritage",
    "Music Promotions Manager - Arts Administration",
    "Music Therapist - Therapists",
    "Musical Instrument Technologist - Music Technology",
    "Musician - Classical - Music",
    "Musician - Popular - Music",
    "Nail Technician - Beauty",
    "Nanny - Childcare and Education",
    "Nanotechnologist - Chemistry and Materials Engineering - Physics",
    "Nature Conservationist - Environmental and Rural Resource Management",
    "Naturopath - Alternative Medicine",
    "Naval Architect - Naval Architecture and Marine Engineering",
    "Network Architect - Systems and Networks",
    "Network Engineer - Systems and Networks - Digital and Technology",
    "Neurophysiologist - Medical Technology",
    "Nuclear Engineer - Offshore and Energy",
    "Nurse - Adult - Nursing and Auxiliary Work",
    "Nurse - Child - Nursing and Auxiliary Work",
    "Nurse - District - Nursing and Auxiliary Work",
    "Nurse - General Practice - Nursing and Auxiliary Work",
    "Nurse - Learning Disabilities - Nursing and Auxiliary Work",
    "Nurse - Mental Health - Nursing and Auxiliary Work",
    "Nursing Support Worker - Nursing and Auxiliary Work",
    "Nutritionist - Food Science and Technology",
    "Occupational Therapist - Occupational Therapy",
    "Occupational Therapy Support Worker - Occupational Therapy",
    "Oceanographer - Earth Studies",
    "Office Manager - Administration and Management General",
    "Offshore Chemist - Chemistry and Materials Engineering - Subsurface Scientists",
    "Offshore Installation Manager - Offshore Based",
    "Offshore Medic - Nursing and Auxiliary Work - Offshore Based",
    "Offshore Service Technician - Offshore and Energy - Offshore Based",
    "Offshore Technician – Cable and Pipelay - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Offshore Technician – Specialised Tools - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Operating Department Practitioner - Medical Technology",
    "Operational Researcher - Mathematics and Statistics",
    "Optical Assistant - Retail and Sales",
    "Optical Technician - Manufacturing General",
    "Optometrist - Ophthalmics and Orthoptics",
    "Orthodontist - Dentistry",
    "Orthoptist - Ophthalmics and Orthoptics",
    "Osteopath - Alternative Medicine",
    "Outdoor Activities Instructor or Leader - Sport and Fitness",
    "Painter and Decorator - Construction Crafts",
    "Paralegal - Legal Support Services",
    "Paramedic - Ambulance Services",
    "Parking Warden - Police and Security Work",
    "Parliamentary Assistant - Politics",
    "Patent Attorney - Patent Work",
    "Patent Examiner - Patent Work",
    "Pattern Cutter or Grader - Clothing and Textiles",
    "Personal Assistant - Administration and Management General",
    "Personal Trainer - Sport and Fitness",
    "Pest Control Technician - Environmental Services",
    "Pet Shop Assistant - Retail and Sales",
    "Petroleum or Reservoir Engineer - Offshore and Energy",
    "Pharmacist - Pharmacy",
    "Pharmacologist - Biology",
    "Pharmacy Support Worker - Pharmacy",
    "Pharmacy Technician - Pharmacy",
    "Phlebotomist - Nursing and Auxiliary Work",
    "Photographer - Photography",
    "Photographic Stylist - Photography",
    "Physicist - Physics",
    "Physiotherapist - Physiotherapy",
    "Physiotherapy Support Worker - Physiotherapy",
    "Piano Tuner - Music Technology",
    "Picture Framer - 3 Dimensional Design",
    "Picture Researcher - Advertising, Marketing and PR",
    "Plant Operator - Construction Crafts",
    "Plasterer - Construction Crafts",
    "Play Therapist - Therapists",
    "Playworker or Play Leader - Childcare and Education",
    "Plumber - Construction Crafts",
    "Podiatrist - Podiatry",
    "Podiatry Support Worker - Podiatry",
    "Police Officer - Police and Security Work",
    "Port Operative - Sea Transport",
    "Post Office Customer Service Consultant - Public Services Administration",
    "Postie - Distribution",
    "PR and Communications Officer - Advertising, Marketing and PR",
    "Pre-press Operator - Printing",
    "Previsualisation Artist - Fine Art or Graphic Design",
    "Print Finisher or Bookbinder - Printing",
    "Print Production Planner - Printing",
    "Prison Officer - Prison Work",
    "Private Tutor - Teaching",
    "Procurator Fiscal - Law (Professional)",
    "Procurement Administrator - Buying",
    "Procurement Manager - Buying",
    "Producer – Radio - Media and Broadcasting",
    "Producer – TV or Film - Media and Broadcasting",
    "Product Designer - 3 Dimensional Design",
    "Production Assistant - Media and Broadcasting",
    "Production Controller or Manager - Manufacturing General",
    "Production Worker - Manufacturing General",
    "Project Engineer - Engineers and Engineering Operatives or Technicians",
    "Project Manager - Business, Management, Admin and Support",
    "Prop Master - Drama and Theatre Technology",
    "Proposals Coordinator - Business, Management, Admin and Support",
    "Prosthetic or Orthotic Support Worker - Medical Technology",
    "Prosthetist or Orthotist - Medical Technology",
    "Psychologist - Psychology and Counselling",
    "Psychologist - Clinical - Psychology and Counselling",
    "Psychologist - Counselling - Psychology and Counselling",
    "Psychologist - Educational - Psychology and Counselling",
    "Psychologist - Forensic - Psychology and Counselling",
    "Psychologist - Health - Psychology and Counselling",
    "Psychologist - Occupational - Psychology and Counselling",
    "Psychologist - Sport and Exercise - Psychology and Counselling",
    "Psychotherapist - Psychology and Counselling",
    "Quality Control Technician - Manufacturing General",
    "Quarry Engineer - Engineering General",
    "Radiographer - Diagnostic - Radiography",
    "Radiographer - Therapeutic - Radiography",
    "Radiography Support Worker - Radiography",
    "Railway Maintenance Engineering Technician - Rail Transport",
    "Railway Maintenance Engineering Technician - Overhead Line - Rail Transport",
    "Railway Maintenance Engineering Technician - Signalling - Rail Transport",
    "Railway Maintenance Engineering Technician - Telecoms - Rail Transport",
    "Railway Maintenance Engineering Technician - Track - Rail Transport",
    "Railway Station Assistant - Rail Transport",
    "Ramp Agent - Air Transport",
    "Receptionist - Administration and Management General",
    "Recruitment Consultant - Administration and Management General",
    "Recycling Operative - General Services",
    "Reflexologist - Wellbeing",
    "Refrigeration Engineer - Engineering General",
    "Refuse Collector - General Services",
    "Registrar of Births, Deaths, Marriages and Civil Partnerships - Public Services Administration",
    "Rehabilitation Engineering Technician - Medical Technology",
    "Removals Operative - Distribution",
    "Renewable Energy Consultant - Environmental Services",
    "Renewable Energy Engineer - Offshore and Energy",
    "Reprographic Assistant - Printing",
    "Reservoir Engineer - Subsurface Scientists",
    "Resort Representative - Travel and Tourism",
    "Respiratory Physiologist - Medical Technology",
    "Restaurant Manager - Hospitality",
    "Retail Assistant - Retail and Sales",
    "Retail Buyer - Buying",
    "Retail Manager - Retail and Sales",
    "Revenue and Customs Officer - Public Services Administration",
    "Riding Instructor - Work with Animals",
    "Risk Manager - Business, Management, Admin and Support",
    "Road Worker - Construction Crafts",
    "Roadie - Media and Broadcasting",
    "Robotics Engineer - Programming and Development - Electrical and Electronic Engineering - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Roof Sheeter and Cladder - Construction Crafts",
    "Roofer - Construction Crafts",
    "Roofer – Felt - Construction Crafts",
    "Room Attendant - Hospitality",
    "Roustabout - Offshore and Energy",
    "ROV Pilot Technician - Offshore and Energy",
    "Royal Air Force Airman or Airwoman - Armed Services",
    "Royal Air Force Officer - Armed Services",
    "Royal Marine - Armed Services",
    "Royal Marines Officer - Armed Services",
    "Royal Navy Officer - Armed Services",
    "Royal Navy Rating - Armed Services",
    "Runner - Media and Broadcasting",
    "Sales Representative - Retail and Sales",
    "Scaffolder - Construction Crafts",
    "Scenic Artist - Drama and Theatre Technology",
    "School Janitor - Facilities Management",
    "Scientific or Technical Illustrator - Fine Art or Graphic Design",
    "Scottish SPCA Animal Rescue Officer - Work with Animals",
    "Scottish SPCA Inspector - Work with Animals",
    "Scrum Master - Business, Management, Admin and Support",
    "Sculptor - 3 Dimensional Design - Fine Art or Graphic Design",
    "Security Officer or Guard - Police and Security Work",
    "Security Systems Installer - Electrical and Electronic Engineering",
    "SEO Specialist - Advertising, Marketing and PR",
    "Set Designer - Drama and Theatre Technology - Interior Design or Display",
    "Sewing Machinist - Clothing and Textiles",
    "Sheet Metal Worker - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Sheriff Officer or Messenger-at-Arms - Legal Support Services",
    "Shoe Repairer - Personal Services",
    "Shopfitter - Construction Crafts",
    "Signaller - Rail Transport",
    "Signwriter - Fine Art or Graphic Design",
    "Smart Meter Engineer - Engineering General",
    "Social Worker - Social Work or Social Care",
    "Software Engineer or Developer - Programming and Development - Digital and Technology",
    "Software Tester - Programming and Development",
    "Solicitor - Law (Professional)",
    "Sound Technician - Music Technology - Media and Broadcasting",
    "Special Effects Technician - Media and Broadcasting",
    "Speech and Language Therapist - Speech Therapy",
    "Speech and Language Therapy Support Worker - Speech Therapy",
    "Sport and Exercise Scientist - Sports Science",
    "Sports Coach or Instructor - Sport and Fitness",
    "Sports Development Officer - Sport and Fitness",
    "Sports or Leisure Centre Assistant - Sport and Fitness",
    "Sports or Leisure Centre Manager - Sport and Fitness",
    "Sports Professional - Sports Performance",
    "Sports Therapist - Sports Science",
    "Stablehand or Groom - Work with Animals",
    "Stage Manager - Drama and Theatre Technology - Media and Broadcasting",
    "Stagehand - Drama and Theatre Technology - Media and Broadcasting",
    "Statistician - Mathematics and Statistics",
    "Steeplejack - Construction Crafts",
    "Stockbroker - Financial Services",
    "Stonemason - Construction Crafts",
    "Store Detective - Police and Security Work",
    "Storyboard Artist - Fine Art or Graphic Design",
    "Street Cleaning Operative - General Services",
    "Structural Engineer - Civil and Structural Engineering",
    "Structural Engineering Technician - Civil and Structural Engineering",
    "Stunt Performer - Drama and Theatre Technology",
    "Sub-editor — Journalism - Journalism",
    "Subsea Engineer - Offshore and Energy",
    "Supermarket Assistant - Retail and Sales",
    "Tailor or Dressmaker - Fashion or Textile Design",
    "Tax Officer - Public Services Administration",
    "Taxi or Car Driver - Road Transport",
    "Teacher - Additional Support for Learning",
    "Teacher - Primary or Early Years",
    "Teacher - Secondary School - Art and Design",
    "Teacher - Secondary School - Biology",
    "Teacher - Secondary School - Business Education",
    "Teacher - Secondary School - Chemistry",
    "Teacher - Secondary School - Computing",
    "Teacher - Secondary School - Design and Technology",
    "Teacher - Secondary School - Drama",
    "Teacher - Secondary School - English",
    "Teacher - Secondary School - Gaelic",
    "Teacher - Secondary School - Geography",
    "Teacher - Secondary School - History",
    "Teacher - Secondary School - Home Economics",
    "Teacher - Secondary School - Mathematics",
    "Teacher - Secondary School - Modern Foreign Languages",
    "Teacher - Secondary School - Modern Studies",
    "Teacher - Secondary School - Music",
    "Teacher - Secondary School - Physical Education",
    "Teacher - Secondary School - Physics",
    "Teacher - Secondary School - Religious Education",
    "Teacher of English as a Foreign Language",
    "Technical Author - Publishing and Writing",
    "Technical Brewer - Food Science and Technology",
    "Technical Distiller - Food Science and Technology",
    "Technical Support Engineer (Onshore/Offshore)",
    "Tendering Officer - Business, Management, Admin and Support",
    "Test Engineer - Programming and Development",
    "Textile Designer - Fashion or Textile Design",
    "Textile Operative - Clothing and Textiles",
    "Theatre Support Worker",
    "Therapist",
    "Therapists",
    "Therapist - Art",
    "Therapist - Dance",
    "Therapist - Drama",
    "Therapist - Music",
    "Ticket Inspector - Transport and Logistics",
    "Tour Guide - Travel and Tourism",
    "Tour Leader or Manager - Travel and Tourism",
    "Town Planner - Town and Regional Planning",
    "Trade Union Official - Public Services Administration",
    "Trading Standards Officer - Public Services Administration",
    "Train Conductor - Rail Transport",
    "Train Driver - Rail Transport",
    "Train Maintenance Technician - Rail Transport",
    "Training and Competency Officer or Manager - Human Resource Management",
    "Translator - Languages",
    "Travel Agency Manager - Travel and Tourism",
    "Travel Consultant - Travel and Tourism",
    "TV or Film Director - Media and Broadcasting",
    "TV or Radio Presenter - Media and Broadcasting",
    "Tyre or Exhaust Fitter - Vehicle Maintenance and Repair",
    "Upholsterer - Furniture",
    "User Experience (UX) Designer - Web and Multimedia",
    "Vehicle Body Repairer - Vehicle Maintenance and Repair",
    "Vehicle Breakdown Engineer - Vehicle Maintenance and Repair",
    "Vehicle Examiner - Police and Security Work - Vehicle Maintenance and Repair",
    "Vehicle MET Technician - Vehicle Maintenance and Repair",
    "Vehicle Parts Advisor - Vehicle Maintenance and Repair",
    "Vehicle Salesperson - Retail and Sales",
    "Vehicle Spray Painter - Vehicle Maintenance and Repair",
    "Veterinary Nurse - Work with Animals",
    "Veterinary Surgeon - Work with Animals",
    "Virtual Assistant - Administration and Management General",
    "Virtual Reality/Augmented Reality Developer - Web and Multimedia",
    "Visitor Attraction Manager - Travel and Tourism",
    "Visitor Services Adviser - Travel and Tourism",
    "Visual Merchandiser - Interior Design or Display - Retail and Sales",
    "Waiter or Waitress - Hospitality",
    "Wall and Floor Tiler - Construction Crafts",
    "Warden or Housing Support Officer - Social Work or Social Care",
    "Wardrobe Assistant - Film, TV or Theatre",
    "Warehouse Operative - Distribution",
    "Waste Energy Engineer - Offshore and Energy",
    "Watch and Clock Repairer - Personal Services",
    "Water or Waste Water Network Operative - Civil and Structural Engineering",
    "Water or Waste Water Treatment Operative - Civil and Structural Engineering",
    "Waterway Operative - Sea Transport",
    "Web Designer - Web and Multimedia",
    "Web Developer - Web and Multimedia",
    "Welder - Mechanical and Manufacturing Engineering (including Fabrication and Welding)",
    "Well Engineer - Engineers and Engineering Operatives or Technicians",
    "Wind Turbine Technician - Offshore and Energy - Engineers and Engineering Operatives or Technicians",
    "Window Fitter - Construction Crafts",
    "Wood Machinist - Furniture",
    "Writer or Author - Publishing and Writing",
    "Yoga Teacher - Sport and Fitness",
    "Youth Worker - Community Work",
    "Zookeeper - Work with Animals",
    "Zoologist - Biology - Work with Animals"
]

import re

def process_role(raw: str) -> list:
    """
    Process a raw role string:
      1. Split at the first hyphen and take the substring before it.
      2. If the resulting string contains "or" (case-insensitive), split it into parts.
      3. Return a list of clean role strings.
    """
    # Step 1: Get substring before the first hyphen
    base = raw.split('-')[0].strip()
    # Step 2: Check if "or" is present (using word boundaries)
    if re.search(r"\bor\b", base, flags=re.IGNORECASE):
        parts = re.split(r"\s+or\s+", base, flags=re.IGNORECASE)
        return [part.strip() for part in parts if part.strip()]
    else:
        return [base]

# Process each raw role and flatten the list
processed_roles = []
for role in _RAW_ROLES:
    processed_roles.extend(process_role(role))

# Remove duplicates while preserving order
KNOWN_ROLES = list(dict.fromkeys(processed_roles))


# Uncomment below to see the output when running this file directly.
if __name__ == "__main__":
    print("KNOWN_ROLES:")
    for r in KNOWN_ROLES:
        print("-", r)